### ISSUE TITLE
Fails to build on Ubuntu 18.04 with gcc-7

### ISSUE THREAD

**Issue by alexmyczko** [thierry-sousbie/DisPerSE#6]
Built fine on Ubuntu 16.04, however with Ubuntu 18.04, there's the xlocale.h gone (glibc 2.26 dropped it),
and then here it fails:

Note: Still builds fine with gcc-6

In file included from /scratch/disperse/new/disperse-0.9.24/src/mse/mse.cpp:65:0:
/scratch/disperse/new/disperse-0.9.24/src/mse/NDfield_network.hxx: In instantiation of âfloat* NDfield_network<cellType>::getPition(cellType, float*) const [with cellType = cellIdentity<>]â:
/scratch/disperse/new/disperse-0.9.24/src/mse/mse.cpp:1140:1:   required from here
/scratch/disperse/new/disperse-0.9.24/src/mse/NDfield_network.hxx:524:14: error: call of overloaded âabs(uint)â is ambiguous       if (abs(c0[j]-coordsI[j])<(net->dims[j]>>1))
           ~~~^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/cstdlib:75:0,
                 from /usr/include/c++/7/stdlib.h:36,
                 from /scratch/disperse/new/disperse-0.9.24/src/mse/mse.cpp:47:
/usr/include/stdlib.h:837:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/include/c++/7/cstdlib:77:0,
                 from /usr/include/c++/7/stdlib.h:36,
                 from /scratch/disperse/new/disperse-0.9.24/src/mse/mse.cpp:47:
/usr/include/c++/7/bits/std_abs.h:56:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
/usr/include/c++/7/bits/std_abs.h:61:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/include/c++/7/bits/std_abs.h:70:3: note: candidate: constexpr double std::abs(double)
   abs(double __x)
   ^~~
/usr/include/c++/7/bits/std_abs.h:74:3: note: candidate: constexpr float std::abs(float)
   abs(float __x)
   ^~~
/usr/include/c++/7/bits/std_abs.h:78:3: note: candidate: constexpr long double std::abs(long double)
   abs(long double __x)
   ^~~
/usr/include/c++/7/bits/std_abs.h:84:3: note: candidate: constexpr __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
/usr/include/c++/7/bits/std_abs.h:102:3: note: candidate: constexpr __float128 std::abs(__float128)
   abs(__float128 __x)
   ^~~
src/mse/CMakeFiles/mse.dir/build.make:65: recipe for target 'src/mse/CMakeFiles/mse.dir/mse.cpp.o' failed
make[3]: *** [src/mse/CMakeFiles/mse.dir/mse.cpp.o] Error 1
make[3]: Leaving directory '/scratch/disperse/new/disperse-0.9.24/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:131: recipe for target 'src/mse/CMakeFiles/mse.dir/all' failed
make[2]: *** [src/mse/CMakeFiles/mse.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/scratch/disperse/new/disperse-0.9.24/obj-x86_64-linux-gnu'

**Comment by nicola-malavasi** [comment]
Hello,

we had the same issue when compiling DisPerSE on Debian 10 with gcc-8.3.

We solved the problems by creating a symbolic link from /usr/include/locale.h to /usr/include/xlocale.h and by modifying the problematic line of code in /src/mse/NDfield_network.hxx at line 524:

`if (abs(c0[j]-coordsI[j])<(net->dims[j]>>1))`

was changed to

`if (abs (static_cast<long long int>(c0[j]-coordsI[j]))<(net->dims[j]>>1))`

following https://stackoverflow.com/questions/50301469/g-error-call-of-overloaded-absunsigned-int-is-ambiguous

WARNING: With this workaround DisPerSE compiles and runs, but it may or may not give the same results as before the modifications. Tests are needed to check that results after the modifications are the same as before.

Hope this is somehow still useful.

**Comment by AwfulJamBalaYa** [comment]
> Hello,
> 
> we had the same issue when compiling DisPerSE on Debian 10 with gcc-8.3.
> 
> We solved the problems by creating a symbolic link from /usr/include/locale.h to /usr/include/xlocale.h and by modifying the problematic line of code in /src/mse/NDfield_network.hxx at line 524:
> 
> `if (abs(c0[j]-coordsI[j])<(net->dims[j]>>1))`
> 
> was changed to
> 
> `if (abs (static_cast<long long int>(c0[j]-coordsI[j]))<(net->dims[j]>>1))`
> 
> following https://stackoverflow.com/questions/50301469/g-error-call-of-overloaded-absunsigned-int-is-ambiguous
> 
> WARNING: With this workaround DisPerSE compiles and runs, but it may or may not give the same results as before the modifications. Tests are needed to check that results after the modifications are the same as before.
> 
> Hope this is somehow still useful.

The method you provided doesn't work on Ubuntu20.04 with gcc-9.
The best way to install disperse on Ubuntu 20.04 is to install gcc-6, following these steps:
1. `vim /etc/apt/sources.list` 
     add: `deb http://dk.archive.ubuntu.com/ubuntu/ bionic main universe`
2. `sudo apt update && sudo apt install g++-6`
3. `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 50 --slave /usr/bin/g++ g++ /usr/bin/g++-6`
4. `sudo update-alternatives --config gcc` and type the corresponding number to choose gcc6.
5. `gcc -v` to check the version of gcc.
6. Type `sudo ln -s /usr/include/locale.h /usr/include/xlocale.h` to creating a symbolic link.
Now you can install disperse (without pdview) easily.😃

Well, if you insist using pdview on Ubuntu 20.04, which no longer officially support qt4, you can follow the steps below to install mathgl1.11 with qt4 enabled.
1. add a third party ppa and install qt4: `sudo add-apt-repository ppa:rock-core/qt4`
    `sudo apt update && sudo apt install libqt4*`
2. Download [gsl1.15.tar.gz](https://ftp.gnu.org/gnu/gsl/gsl-1.15.tar.gz)
3. If you have installed gsl of higher version, you can go to the directory after extracting the tar.gz file, and type `./configure --prefix=/YOUR_DIRECTORY && make -j && make install` to install gsl1.15 in the specific directory
4. edit the ~/.bashrc to add the following sentences: 
`export gsl_DIR=YOUR_DIRECTORY/bin:$PATH` 
`export PKG_CONFIG_PATH=YOUR_DIRECTORY/lib/pkgconfig:$PKG_CONFIG_PATH` 
`export PATH=$PATH:YOUR_DIRECTORY/bin` 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:YOUR_DIRECTORY/lib` 
`export LIBRARY_PATH=$LIBRARY_PATH::YOUR_DIRECTORY/lib` 
`export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:YOUR_DIRECTORY/include` 
`export C_INCLUDE_PATH=$C_INCLUDE_PATH:YOUR_DIRECTORY/include` 
`export GSL_LD=YOUR_DIRECTORY/lib` 
5. `source ~/.bashrc`
6. if everything is OK, then type `pkg-config --libs gsl` in the terminal, it will return: `-L/YOUR_DIRECTORY/lib -lgsl -lgslcblas -lm`
7. go to the directory of the extracted mathgl1.11.3 files, type: `./configure CFLAGS'=-L/YOUR_DIRECTORY/lib -lgsl -lgslcblas -lm' --enable-qt && sudo make && sudo make install`
8. At this moment, you are ready to install DisPerSE (specify the gsl installed directory by adding `-DGSL_DIR=YOUR_DIRECTORY` after `cmake../)`😃

REFERENCE:
[https://askubuntu.com/questions/1236552/how-can-i-downgrade-gcc-to-version-6-on-20-04](https://askubuntu.com/questions/1236552/how-can-i-downgrade-gcc-to-version-6-on-20-04)
[https://launchpad.net/~rock-core/+archive/ubuntu/qt4/](https://launchpad.net/~rock-core/+archive/ubuntu/qt4/)

**Comment by alexmyczko** [comment]
Meanwhile Debian is moving to gcc-10, to be useful for future Ubuntu releases the code would need some updates...
